### ISSUE TITLE
Re design default template

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-templates#15]
Discuss a new 'empty' default template to replace the two gui templates. 
More questions should be asked, like : 
- How many pages ? 
- The name of the pages ?
- use scenario management or version management (so we run Core service)
- expose rest APIS (so we run Rest service)
- and others

**Comment by trgiangdo** [comment]
The requirement documentation for the default template (to be discuss):
https://docs.google.com/document/d/1tyeOaKDzP5PDrRdgBC5y1SOnQGe8f0Nf0BaE4p7m38I
