### ISSUE TITLE
Apply latest changes in Core elements in app templates

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-templates#33]
[PR 27](https://github.com/Avaiga/taipy-templates/pull/27) has some layout issues (see [Taipy issue 277](https://github.com/Avaiga/taipy/issues/277)). 
This was fixed and need to be propagated.

Another problem in templates is the use of the non-recommended `import *` construct, that needs to be taken care of.

**Comment by jrobinAV** [comment]
The default behavior solves the issue.
