### ISSUE TITLE
Taipy logo in taipy templates does not fit dark mode

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-templates#36]
When creating an app from a template, the app has the Taipy logo on a white background by default. The logo occupies a lot of space, and its white square background does not fit with dark mode. It should either be removed or changed.

![image](https://github.com/Avaiga/taipy/assets/62465003/c9a40414-3995-4437-aad0-2fb5bc598c25)

**Comment by jrobinAV** [comment]
That does not solve your issue but I thought the picture was removed from the template. Which version of `taipy-templates` are you using? The logo should not be in the template. As a user, the first thing I would do is to remove it. It just slows down my development process to have a picture displayed by default.

**Comment by AlexandreSajus** [comment]
I was probably using taipy==2.4.0. If the image has been removed then perfect, you can close this issue
